### PR TITLE
StreamLicensing patch

### PR DESCRIPTION
**Pull request by meyskens**
StreamLicensing uses the general overview API which was not implemented yet

---
This change is [Reviewable](https://reviewable.io/reviews/innovate-technologies/cast/14)

### CODE REVIEW

**Comment by meyskens** [comment]
JSON works, working on XML now

**Comment by meyskens** [comment]
XML works, still no validation. Will get in touch with them.

**Comment by leoetlino** [comment]
Is there any update for this?

**Comment by meyskens** [comment]
Radio silence from their side. Will close this for now.

**Pull request closed without merging**
