### PR TITLE
Added simple ASX file

### PR DESCRIPTION
**Pull request by meyskens**
To do:
- [x] Add title
- [x] Test in WMP

[Review on Reviewable](https://reviewable.io/reviews/innovate-technologies/cast/11)

### CODE REVIEW

**Comment by leoetlino** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[intern/streams/httphandler.js, line 267 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/11#-KBTGMYHEhQF1UG3dmxR:-KBTGMYHEhQF1UG3dmxS:-261821292) ([raw file](https://github.com/innovate-technologies/cast/blob/0822599e91b030b069440b018249617cfb2236f1/intern/streams/httphandler.js#L267)):*
space before parenthesis

---

*[intern/streams/httphandler.js, line 269 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/11#-KBTFoRSzW2bPw-ZoTBc:-KBTFoRSzW2bPw-ZoTBd:-26920435) ([raw file](https://github.com/innovate-technologies/cast/blob/0822599e91b030b069440b018249617cfb2236f1/intern/streams/httphandler.js#L269)):*
`!stream` should be safe enough

---

*[intern/streams/httphandler.js, line 275 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/11#-KBTFtIlVLs5EZFlzPxq:-KBTFtIlVLs5EZFlzPxr:57513322) ([raw file](https://github.com/innovate-technologies/cast/blob/0822599e91b030b069440b018249617cfb2236f1/intern/streams/httphandler.js#L275)):*
Consider using ES6 `` strings to make it more readable and to remove the need for escaping.

Example:

    res.send(`<asx version="3.0"><entry><ref href="${global.config.hostname}/streams/${stream}"/></entry></asx>`);

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovate-technologies/cast/11)*

**Comment by meyskens** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[intern/streams/httphandler.js, line 267 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/11#-KBTGMYHEhQF1UG3dmxR:-KBTKpuvgl2OZmgeYcGj:902661122) ([raw file](https://github.com/innovate-technologies/cast/blob/0822599e91b030b069440b018249617cfb2236f1/intern/streams/httphandler.js#L267)):*
this is the non-refactor version

---

*[intern/streams/httphandler.js, line 275 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/11#-KBTFtIlVLs5EZFlzPxq:-KBTKm3Mcae2emg7XB_m:-261099019) ([raw file](https://github.com/innovate-technologies/cast/blob/0822599e91b030b069440b018249617cfb2236f1/intern/streams/httphandler.js#L275)):*
This is the ES5 build still

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovate-technologies/cast/11)*

**Comment by meyskens** [comment]
Related: [control/24](https://github.com/Innovate-Technologies/control/pull/24)

**Comment by meyskens** [comment]
Tested and works fine
WMP screenshot

**Comment by ncborges** [comment]
Can we have the links for ASX on the control panel as we have the .pls and .m3u,please?

**Comment by leoetlino** [comment]
@ncborges yes, that is in PR innovate-technologies/control#24 and will be there once this PR is merged.

**Pull request merged**
