### PR TITLE
Add Icecast input

### PR DESCRIPTION
**Pull request by meyskens**
Added an Icecast input source. Since it is built on top of HTTP this is proxyable through Nginx and will probably be the preferred input soon. 

To do 
- [x] Add metadata
- [x] Test with other encoders than Nicecast
- [x] Add metadata route to Express for Nginx proxy
- [x] Test over Nginx

---
This change is [Reviewable](https://reviewable.io/reviews/innovate-technologies/cast/22)

### CODE REVIEW

**Comment by leoetlino** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 14 unresolved discussions.

---

*[intern/HTTP/apps/icecast.js, line 63 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxkF3KqC3pmjLnLWyl:-KKxkF3KqC3pmjLnLWym:-474945539) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/HTTP/apps/icecast.js#L63)):*
> ```JavaScript
>         }
>         res.set("Content-Type", "text/xml");
>         res.send("<?xml version=\"1.0\"?>\n<iceresponse><message>Metadata update successful</message><return>1</return></iceresponse>")
> ```

maybe use ` to avoid having to escape " (so it's more readable)?

---

*[intern/inputParser/icecast.js, line 6 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxkk2LD6zAmvcuYPjZ:-KKxkk2LD6zAmvcuYPj_:-1919342942) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L6)):*
> ```JavaScript
> }
> 
> const listener = tcp.createServer((c) => {
> ```

the variable name could probably be better than just c

---

*[intern/inputParser/icecast.js, line 9 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxkgOI_UuTMkCb8yim:-KKxkgOI_UuTMkCb8yin:-470516354) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L9)):*
> ```JavaScript
>     let stream
> 
>     let info = {}
> ```

const

---

*[intern/inputParser/icecast.js, line 16 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxkwf4gxkFbOAf3hk5:-KKxkwf4gxkFbOAf3hk6:-470516354) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L16)):*
> ```JavaScript
> 
>     c.on("data", (data) => {
>         let input = data.toString("utf-8").split("\r\n").join("\n");
> ```

const

---

*[intern/inputParser/icecast.js, line 17 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxkqzqqPpTiYu89nC0:-KKxkqzqqPpTiYu89nC1:471288915) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L17)):*
> ```JavaScript
>     c.on("data", (data) => {
>         let input = data.toString("utf-8").split("\r\n").join("\n");
>         console.log(input)
> ```

this should be removed

---

*[intern/inputParser/icecast.js, line 19 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxktNCl9z0kG28hGe2:-KKxktNDW3Ny0plpukJM:-469765787) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L19)):*
> ```JavaScript
>         console.log(input)
>         if (!gotRequest) {
>             console.log(request)
> ```

ditto

---

*[intern/inputParser/icecast.js, line 20 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxkyOkBtJaxTbaTNHR:-KKxkyOkBtJaxTbaTNHS:-470516354) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L20)):*
> ```JavaScript
>         if (!gotRequest) {
>             console.log(request)
>             let request = input.split(" ")
> ```

const

---

*[intern/inputParser/icecast.js, line 27 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxl37tjCyV8sJ7bqfF:-KKxl37tjCyV8sJ7bqfG:1476430301) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L27)):*
> ```JavaScript
>                 let url = request[1]
>                 let updateStream
>                 for (let id in requestArray) {
> ```

this can be replaced with a for of loop

---

*[intern/inputParser/icecast.js, line 29 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxlBlR4eeri5HVgVvm:-KKxlBlR4eeri5HVgVvn:-1405787243) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L29)):*
> ```JavaScript
>                 for (let id in requestArray) {
>                     if (requestArray.hasOwnProperty(id)) {
>                         if (requestArray[id].toLowerCase().indexOf("authorization") > -1) {
> ```

.includes()

---

*[intern/inputParser/icecast.js, line 35 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxlHw-8ZZueVXabptt:-KKxlHw-8ZZueVXabptu:774669485) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L35)):*
> ```JavaScript
>                             let password = authArray.join("")
>                             if (!streams.streamPasswords.hasOwnProperty(password)) {
>                                 c.write("HTTP/1.1 401 You need to authenticate\n\n")
> ```

does this really send 401?

---

*[intern/inputParser/icecast.js, line 53 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxlQVoEslzvETE3VCR:-KKxlQVoEslzvETE3VCS:-5229621) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L53)):*
> ```JavaScript
>                     })
>                 }
>                 c.write("HTTP/1.1 200 OK\nContent-Type: text/xml; charset=utf-8\n\n<?xml version=\"1.0\"?>\n<iceresponse><message>Metadata update successful</message><return>1</return></iceresponse>")
> ```

duplicate string

---

*[intern/inputParser/icecast.js, line 63 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxlUzKQuN01gR0K0-n:-KKxlUzKQuN01gR0K0-o:-1615178285) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L63)):*
> ```JavaScript
>             let continueNeeded = false
> 
>             for (let id in request) {
> ```

for of

---

*[intern/inputParser/icecast.js, line 142 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxliP1Jf2LMWXsXxis:-KKxliP1Jf2LMWXsXxit:1020646171) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L142)):*
> ```JavaScript
>     })
> 
> })
> ```

actually, the function seems slightly longer than ideal. maybe some parts could be refactored into separate functions?

---

*[intern/inputParser/icecast.js, line 155 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxkaTx0PqG-QNFy0h9:-KKxkaTx0PqG-QNFy0hA:919572522) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L155)):*
> ```JavaScript
> 
> 
> module.exports.listenOn = (port) => {
> ```

export const listenOn

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/cast/22)*

**Comment by meyskens** [comment]
Review status: 4 of 5 files reviewed at latest revision, 14 unresolved discussions.

---

*[intern/inputParser/icecast.js, line 6 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxkk2LD6zAmvcuYPjZ:-KKxnPLMtUrOUaNWL_TG:970282746) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L6)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> the variable name could probably be better than just c
</details>
c stands for connection, is used as it is used a lot. (same in SHOUTcast.js)

---

*[intern/inputParser/icecast.js, line 17 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxkqzqqPpTiYu89nC0:-KKxn_imJ2i9NYOsBmUa:-449684310) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L17)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> this should be removed
</details>
How did it get there... was removed in the latest commit

---

*[intern/inputParser/icecast.js, line 19 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxktNCl9z0kG28hGe2:-KKxndjQjE48oOEtf1qC:678021867) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L19)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> ditto
</details>
same

---

*[intern/inputParser/icecast.js, line 35 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxlHw-8ZZueVXabptt:-KKxniY77VwtI50f8epi:532173509) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L35)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> does this really send 401?
</details>
http://cast.readme.io/docs/icecast yep

---

*[intern/inputParser/icecast.js, line 142 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxliP1Jf2LMWXsXxis:-KKxnqpKnObnV6zRWSPy:611580991) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L142)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> actually, the function seems slightly longer than ideal. maybe some parts could be refactored into separate functions?
</details>
hard to since a lot of variable need to be accessed 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/cast/22)*

**Comment by meyskens** [comment]
Review status: 4 of 5 files reviewed at latest revision, 14 unresolved discussions.

---

*[intern/HTTP/apps/icecast.js, line 63 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxkF3KqC3pmjLnLWyl:-KKxoXahfd0bIk13xY2d:-499146009) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/HTTP/apps/icecast.js#L63)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> maybe use ` to avoid having to escape " (so it's more readable)?
</details>
Done.

---

*[intern/inputParser/icecast.js, line 17 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxkqzqqPpTiYu89nC0:-KKxocspvcwOQoorYhjO:-499146009) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L17)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> How did it get there... was removed in the latest commit
</details>
Done.

---

*[intern/inputParser/icecast.js, line 20 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxkyOkBtJaxTbaTNHR:-KKxotnjQdg5rX56xsvm:-499146009) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L20)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> const
</details>
Done.

---

*[intern/inputParser/icecast.js, line 27 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxl37tjCyV8sJ7bqfF:-KKxou8M0yQOV1J6j1jG:-499146009) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L27)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> this can be replaced with a for of loop
</details>
Done.

---

*[intern/inputParser/icecast.js, line 29 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxlBlR4eeri5HVgVvm:-KKxoxuFHL1twyWTFSlI:-499146009) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L29)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> .includes()
</details>
Done.

---

*[intern/inputParser/icecast.js, line 35 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxlHw-8ZZueVXabptt:-KKxoyjQdZYoa5bf0rwK:-499146009) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L35)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> http://cast.readme.io/docs/icecast yep
</details>
Done.

---

*[intern/inputParser/icecast.js, line 53 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxlQVoEslzvETE3VCR:-KKxoziVeXPx7D2kJ7ve:-123738550) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L53)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> duplicate string
</details>
In a different code part

---

*[intern/inputParser/icecast.js, line 63 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxlUzKQuN01gR0K0-n:-KKxpD1jIFEsd4tHY9MY:-1620827760) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L63)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> for of
</details>
id is needed in one of the conditions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/cast/22)*

**Comment by meyskens** [comment]
Review status: 2 of 5 files reviewed at latest revision, 14 unresolved discussions.

---

*[intern/inputParser/icecast.js, line 9 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxkgOI_UuTMkCb8yim:-KKxpk_fSMsa2O_OcgWX:-499146009) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L9)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> const
</details>
Done.

---

*[intern/inputParser/icecast.js, line 16 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxkwf4gxkFbOAf3hk5:-KKxplQAfP9LCy97Xf67:-499146009) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L16)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> const
</details>
Done.

---

*[intern/inputParser/icecast.js, line 19 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxktNCl9z0kG28hGe2:-KKxpns8LnnMk6CN3eQf:-499146009) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L19)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> same
</details>
Done.

---

*[intern/inputParser/icecast.js, line 53 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxlQVoEslzvETE3VCR:-KKxppWOTlQhxjz9gcQ9:-499146009) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L53)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> In a different code part
</details>
Done.

---

*[intern/inputParser/icecast.js, line 63 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxlUzKQuN01gR0K0-n:-KKxppJ1PtFswGRD3MUJ:-499146009) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L63)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> id is needed in one of the conditions
</details>
Done.

---

*[intern/inputParser/icecast.js, line 155 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/cast/22#-KKxkaTx0PqG-QNFy0h9:-KKxpr9jwG7fK94sDyFU:-499146009) ([raw file](https://github.com/innovate-technologies/cast/blob/ac035011318b083ad94b38e63b8deda8523ae789/intern/inputParser/icecast.js#L155)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> export const listenOn
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/cast/22)*

**Pull request merged**
